"""Bearer-token auth for the AgentSploit web UI.

v1.6 introduces write endpoints (POST /api/jobs/scan, /api/jobs/verify)
and a server-side job runner. Without auth, anyone able to reach the
server can start scans against arbitrary targets and read engagement
artifacts. So v1.6 requires auth by default.

Token model
-----------
- Single shared bearer token generated by `agentsploit serve` on first
  run and persisted at `~/.config/agentsploit/web-token` (chmod 600).
- Sent by clients as `Authorization: Bearer <token>` (or as a
  `?token=` query string for the SSE EventSource browser API, which
  cannot set headers).
- `agentsploit serve --no-auth` disables auth entirely; the server
  prints a loud warning and refuses to bind to non-loopback hosts.

There is no user / role model. Anyone with the token has full access.
This is appropriate for a single-operator engagement tool; multi-user
auth can layer on later if there's demand.
"""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

from fastapi import Header, HTTPException, Query

from agentsploit.utils.logging import get_logger

log = get_logger(__name__)


def _default_token_path() -> Path:
    """Cross-platform location for the persisted bearer token.

    - Linux/macOS: `${XDG_CONFIG_HOME:-$HOME/.config}/agentsploit/web-token`
    - Windows: `%APPDATA%\\agentsploit\\web-token` (or `~/AppData/Roaming` fallback)
    """
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        base = Path(appdata) if appdata else Path.home() / "AppData" / "Roaming"
        return base / "agentsploit" / "web-token"
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) if xdg else Path.home() / ".config"
    return base / "agentsploit" / "web-token"


_TOKEN_DEFAULT_PATH = _default_token_path()


class _AuthState:
    """Module-level auth context, set by build_app() at server startup."""

    token: str | None = None
    """Active bearer token. ``None`` means auth is disabled."""

    enabled: bool = True


def configure(*, token: str | None, enabled: bool) -> None:
    """Set the active auth context. Called from server.build_app()."""
    _AuthState.token = token
    _AuthState.enabled = enabled


def load_or_create_token(token_path: Path | None = None) -> str:
    """Read the persisted token, or mint a new one if absent.

    On POSIX, the file is chmod 600 because it's an unscoped admin secret.
    On Windows, `os.chmod` has no effect on ACLs - we log a warning instead
    of silently failing so operators on shared Windows hosts know the
    token file is governed by the parent directory's NTFS ACL, not by Unix
    mode bits.
    """
    path = token_path or _TOKEN_DEFAULT_PATH
    if path.exists():
        token = path.read_text(encoding="utf-8").strip()
        if token:
            return token
    path.parent.mkdir(parents=True, exist_ok=True)
    token = secrets.token_urlsafe(32)
    path.write_text(token + "\n", encoding="utf-8")
    if sys.platform == "win32":
        log.warning(
            "Windows: cannot chmod 600 the bearer token file at %s. "
            "Token security relies on the parent directory's NTFS ACL.",
            path,
        )
    else:
        try:
            os.chmod(path, 0o600)
        except OSError as e:
            log.warning("Could not chmod 600 token file %s: %s", path, e)
    return token


def require_token(
    authorization: str | None = Header(default=None),
    token_query: str | None = Query(default=None, alias="token"),
) -> None:
    """FastAPI dependency: rejects the request if the bearer token is missing or wrong.

    When auth is disabled (``--no-auth``), this dependency is a no-op
    and every request is allowed.
    """
    if not _AuthState.enabled:
        return

    expected = _AuthState.token
    if expected is None:
        # configure() was never called with a real token but enabled stayed True;
        # treat this as misconfiguration and refuse the request rather than
        # silently letting it through.
        raise HTTPException(
            status_code=503,
            detail="auth is enabled but no token is configured",
        )

    candidate: str | None = None
    if authorization:
        scheme, _, value = authorization.partition(" ")
        if scheme.lower() == "bearer" and value:
            candidate = value.strip()
    if candidate is None and token_query:
        candidate = token_query.strip()

    if candidate is None:
        raise HTTPException(
            status_code=401,
            detail="missing bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    # secrets.compare_digest raises TypeError on non-ASCII str inputs; encode
    # both sides to bytes so a garbage header doesn't crash with HTTP 500.
    if not secrets.compare_digest(candidate.encode("utf-8"), expected.encode("utf-8")):
        raise HTTPException(
            status_code=403,
            detail="invalid bearer token",
        )
